name: Helm CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  helm-validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Helm Lint
        run: |
          helm lint .

      - name: Helm Template Validation
        run: |
          helm template web-app . \
            -f values-prod.yaml
- name: DEV â€“ Deploy to Kubernetes
  run: |
    mkdir -p ~/.kube
    echo "${DEV_KUBECONFIG}" > ~/.kube/config

    helm upgrade --install web-app . \
      -f values-dev.yaml \
      --namespace dev \
      --create-namespace
  env:
    DEV_KUBECONFIG: ${{ secrets.DEV_KUBECONFIG }}